### ISSUE TITLE
Modify init scripts on windows to add dll search directory. 

### ISSUE THREAD

**Issue by Neumann-A** [open-vcpkg/python-registry#22]
The test function does:

`os.add_dll_directory('@DLL_DIR@') if os.name == 'nt' else None`

but that could probably be added top all `__init__.py` scripts of modules

It would need to be something like:

```
import os
import sys
from pathlib import Path

vcpkg_bin_path = Path(sys.prefix + '/../../bin')
if os.name == 'nt' and vcpkg_bin_path.is_dir():
  os.add_dll_directory(vcpkg_bin_path)
```

which avoids adding nonexistent paths.

**Comment by m-kuhn** [comment]
What problem does this solve?

If a consumer exe links to libpython, shouldn't it be up to this to add the dll path on init?

**Comment by Neumann-A** [comment]
> If a consumer exe links to libpython, shouldn't it be up to this to add the dll path on init?

I would assume that `vcpkg_bin_path`  would point somewhere else.

**Comment by m-kuhn** [comment]
I still wonder what the use case is that this solves.

**Comment by Neumann-A** [comment]
Making the imports work for python3

**Comment by Neumann-A** [comment]
> Because it's hard to upstream to vcpkg or because it's a patch?

https://github.com/microsoft/vcpkg/pull/31279

They still think PATH can be used.

**Comment by m-kuhn** [comment]
We could add a small port that installs a [`sitecustomize`](https://docs.python.org/3/library/site.html#module-sitecustomize) script which calls `os.add_dll_directory()`. It's called only once and can be overwritten by users.

**Comment by Neumann-A** [comment]
> We could add a small port that installs a [sitecustomize](https://docs.python.org/3/library/site.html#module-sitecustomize) script which calls os.add_dll_directory(). It's called only once and can be overwritten by users.

example ?

**Comment by Neumann-A** [comment]
Hmm ok that seems to be better but requires to be done by the python3 port
