### ISSUE TITLE
py-psycopg2 compilation fails

### ISSUE THREAD

**Issue by nicogodet** [open-vcpkg/python-registry#60]
I tried to compile QGIS without SDK and I encounter a compilation error on py-psycog2 : pg_config not found

https://github.com/open-vcpkg/python-registry/blob/d489a74130fadbcc56af0c8f9d312a49ca6a7c1a/ports/py-psycopg2/portfile.cmake#L8

In my compilation, pg_config is in `${CURRENT_INSTALLED_DIR}/tools/libpq` not `${CURRENT_INSTALLED_DIR}/tools/libpq/bin`
![image](https://github.com/user-attachments/assets/d01891bf-1276-4106-bde2-502e7c127689)

**Comment by nicogodet** [comment]
In QGIS SDK, pg_config is also in `tools/libpq` and not in `tools/libpq/bin`

**Comment by m-kuhn** [comment]
good find, on macos it's in `tools/libpq/bin`
could you try to copy the folder from https://github.com/open-vcpkg/python-registry/blob/d489a74130fadbcc56af0c8f9d312a49ca6a7c1a/ports/py-psycopg2 into your local QGIS source tree in vcpkg/ports and change this line and see if it fixes the issue?
I am a bit perplexed why this works (given your observation in the sdk), but we could try to change it to

```
if(VCPKG_TARGET_IS_WINDOWS)
  vcpkg_add_to_path("${CURRENT_INSTALLED_DIR}/tools/libpq") 
else()
  vcpkg_add_to_path("${CURRENT_INSTALLED_DIR}/tools/libpq/bin") 
endif()
```

**Comment by nicogodet** [comment]
@m-kuhn Your patch fixes the issue

**Comment by m-kuhn** [comment]
Thanks!
Do you want to open a pull request or I do?
If you do, add a port-version 1 to vcpkg.json

**Comment by nicogodet** [comment]
I can open a PR
